/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Boolean': unknown;
    'CardCompat': { kind: 'OBJECT'; name: 'CardCompat'; fields: { 'info': { name: 'info'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'minute': { name: 'minute'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'player': { name: 'player'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerPreviewCompat'; ofType: null; }; } }; 'type': { name: 'type'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Category': { kind: 'OBJECT'; name: 'Category'; fields: { 'alpha2': { name: 'alpha2'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'country': { name: 'country'; type: { kind: 'OBJECT'; name: 'Country'; ofType: null; } }; 'flag': { name: 'flag'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'CoachCompat': { kind: 'OBJECT'; name: 'CoachCompat'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'CompetitionPlacementCompat': { kind: 'OBJECT'; name: 'CompetitionPlacementCompat'; fields: { 'draw': { name: 'draw'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'goalsConceded': { name: 'goalsConceded'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'goalsDifference': { name: 'goalsDifference'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'goalsScored': { name: 'goalsScored'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'lost': { name: 'lost'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'matches': { name: 'matches'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'points': { name: 'points'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'position': { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'targetCompetitionNames': { name: 'targetCompetitionNames'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'team': { name: 'team'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TeamPreviewCompat'; ofType: null; }; } }; 'won': { name: 'won'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'CompetitionPreviewCompat': { kind: 'OBJECT'; name: 'CompetitionPreviewCompat'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'logo': { name: 'logo'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'CompetitionTableCompat': { kind: 'OBJECT'; name: 'CompetitionTableCompat'; fields: { 'placements': { name: 'placements'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CompetitionPlacementCompat'; ofType: null; }; }; }; } }; 'tableName': { name: 'tableName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Country': { kind: 'OBJECT'; name: 'Country'; fields: { 'alpha2': { name: 'alpha2'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'alpha3': { name: 'alpha3'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'DataStatusCompat': { name: 'DataStatusCompat'; enumValues: 'NONE' | 'LINEUPS' | 'PARTIAL' | 'FULL'; };
    'Event': { kind: 'OBJECT'; name: 'Event'; fields: { 'awayTeam': { name: 'awayTeam'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Team'; ofType: null; }; } }; 'date': { name: 'date'; type: { kind: 'OBJECT'; name: 'EventDate'; ofType: null; } }; 'fixture': { name: 'fixture'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'homeTeam': { name: 'homeTeam'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Team'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'result': { name: 'result'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'EventResult'; ofType: null; }; } }; }; };
    'EventDate': { kind: 'OBJECT'; name: 'EventDate'; fields: { 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'dateISO': { name: 'dateISO'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'time': { name: 'time'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'EventResult': { kind: 'OBJECT'; name: 'EventResult'; fields: { 'awayScore': { name: 'awayScore'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'homeScore': { name: 'homeScore'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'result': { name: 'result'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'EventSeatchResult': { kind: 'OBJECT'; name: 'EventSeatchResult'; fields: { 'event': { name: 'event'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Event'; ofType: null; }; } }; 'score': { name: 'score'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'Float': unknown;
    'GoalCompat': { kind: 'OBJECT'; name: 'GoalCompat'; fields: { 'info': { name: 'info'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'minute': { name: 'minute'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'player': { name: 'player'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerPreviewCompat'; ofType: null; }; } }; }; };
    'ID': unknown;
    'Int': unknown;
    'LineupCompat': { kind: 'OBJECT'; name: 'LineupCompat'; fields: { 'birthDate': { name: 'birthDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'captain': { name: 'captain'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'number': { name: 'number'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'position': { name: 'position'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'rating': { name: 'rating'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'teamId': { name: 'teamId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'MatchByDateCompat': { kind: 'OBJECT'; name: 'MatchByDateCompat'; fields: { 'attendance': { name: 'attendance'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'away': { name: 'away'; type: { kind: 'OBJECT'; name: 'TeamPreviewCompat'; ofType: null; } }; 'competition': { name: 'competition'; type: { kind: 'OBJECT'; name: 'CompetitionPreviewCompat'; ofType: null; } }; 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'dateISO': { name: 'dateISO'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'fixture': { name: 'fixture'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'home': { name: 'home'; type: { kind: 'OBJECT'; name: 'TeamPreviewCompat'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'matchDay': { name: 'matchDay'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'result': { name: 'result'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'time': { name: 'time'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'MatchCompat': { kind: 'OBJECT'; name: 'MatchCompat'; fields: { 'away': { name: 'away'; type: { kind: 'OBJECT'; name: 'TeamPreviewCompat'; ofType: null; } }; 'bench': { name: 'bench'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'LineupCompat'; ofType: null; }; } }; 'cards': { name: 'cards'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'CardCompat'; ofType: null; }; } }; 'colorKitAway': { name: 'colorKitAway'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'colorKitHome': { name: 'colorKitHome'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'competition': { name: 'competition'; type: { kind: 'OBJECT'; name: 'CompetitionPreviewCompat'; ofType: null; } }; 'dataStatus': { name: 'dataStatus'; type: { kind: 'ENUM'; name: 'DataStatusCompat'; ofType: null; } }; 'date': { name: 'date'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'formationAway': { name: 'formationAway'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'formationHome': { name: 'formationHome'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'goals': { name: 'goals'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'GoalCompat'; ofType: null; }; } }; 'hasStatictics': { name: 'hasStatictics'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'home': { name: 'home'; type: { kind: 'OBJECT'; name: 'TeamPreviewCompat'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'lineups': { name: 'lineups'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'LineupCompat'; ofType: null; }; } }; 'matchDay': { name: 'matchDay'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'result': { name: 'result'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'stadium': { name: 'stadium'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MatchStadiumPreviewCompat'; ofType: null; }; } }; 'substitutions': { name: 'substitutions'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'SubstitutionCompat'; ofType: null; }; } }; }; };
    'MatchStadiumPreviewCompat': { kind: 'OBJECT'; name: 'MatchStadiumPreviewCompat'; fields: { 'season': { name: 'season'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'stadiumName': { name: 'stadiumName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'teamId': { name: 'teamId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'venueId': { name: 'venueId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'Player': { kind: 'OBJECT'; name: 'Player'; fields: { 'birthDate': { name: 'birthDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'contractExpiration': { name: 'contractExpiration'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'country': { name: 'country'; type: { kind: 'OBJECT'; name: 'Country'; ofType: null; } }; 'deceased': { name: 'deceased'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'firstName': { name: 'firstName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'foot': { name: 'foot'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'gender': { name: 'gender'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'height': { name: 'height'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lastName': { name: 'lastName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'marketValue': { name: 'marketValue'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'retired': { name: 'retired'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'shirtNumber': { name: 'shirtNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'shortName': { name: 'shortName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'slug': { name: 'slug'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'team': { name: 'team'; type: { kind: 'OBJECT'; name: 'Team'; ofType: null; } }; }; };
    'PlayerPreviewCompat': { kind: 'OBJECT'; name: 'PlayerPreviewCompat'; fields: { 'birthDate': { name: 'birthDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'fullName': { name: 'fullName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'PlayerSearchResult': { kind: 'OBJECT'; name: 'PlayerSearchResult'; fields: { 'player': { name: 'player'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; } }; 'score': { name: 'score'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'dummy': { name: 'dummy'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'getCompetitionTablesCompat': { name: 'getCompetitionTablesCompat'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CompetitionTableCompat'; ofType: null; }; }; }; } }; 'getMatchCompat': { name: 'getMatchCompat'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MatchCompat'; ofType: null; }; } }; 'getMatchesByDateCompat': { name: 'getMatchesByDateCompat'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MatchByDateCompat'; ofType: null; }; }; }; } }; 'player': { name: 'player'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; } }; 'search': { name: 'search'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SearchResult'; ofType: null; }; } }; 'team': { name: 'team'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TeamQuery'; ofType: null; }; } }; 'teamMatchesCompat': { name: 'teamMatchesCompat'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TeamMatchCompat'; ofType: null; }; }; }; } }; }; };
    'SearchResult': { kind: 'OBJECT'; name: 'SearchResult'; fields: { 'matches': { name: 'matches'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'EventSeatchResult'; ofType: null; }; }; }; } }; 'players': { name: 'players'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerSearchResult'; ofType: null; }; }; }; } }; 'teams': { name: 'teams'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TeamSearchResult'; ofType: null; }; }; }; } }; 'uniqueTournaments': { name: 'uniqueTournaments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UniqueTournamentSearchResult'; ofType: null; }; }; }; } }; }; };
    'String': unknown;
    'SubstitutionCompat': { kind: 'OBJECT'; name: 'SubstitutionCompat'; fields: { 'minute': { name: 'minute'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'playerIn': { name: 'playerIn'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerPreviewCompat'; ofType: null; }; } }; 'playerOut': { name: 'playerOut'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerPreviewCompat'; ofType: null; }; } }; 'reason': { name: 'reason'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Team': { kind: 'OBJECT'; name: 'Team'; fields: { 'country': { name: 'country'; type: { kind: 'OBJECT'; name: 'Country'; ofType: null; } }; 'disabled': { name: 'disabled'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'gender': { name: 'gender'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'nameCode': { name: 'nameCode'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'national': { name: 'national'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'primaryUniqueTournament': { name: 'primaryUniqueTournament'; type: { kind: 'OBJECT'; name: 'UniqueTournament'; ofType: null; } }; 'shortName': { name: 'shortName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'slug': { name: 'slug'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'teamColors': { name: 'teamColors'; type: { kind: 'OBJECT'; name: 'TeamColors'; ofType: null; } }; 'tournament': { name: 'tournament'; type: { kind: 'OBJECT'; name: 'Tournament'; ofType: null; } }; }; };
    'TeamColors': { kind: 'OBJECT'; name: 'TeamColors'; fields: { 'primary': { name: 'primary'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'secondary': { name: 'secondary'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'text': { name: 'text'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'TeamMatchCompat': { kind: 'OBJECT'; name: 'TeamMatchCompat'; fields: { 'attendance': { name: 'attendance'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'away': { name: 'away'; type: { kind: 'OBJECT'; name: 'TeamPreviewCompat'; ofType: null; } }; 'coach': { name: 'coach'; type: { kind: 'OBJECT'; name: 'CoachCompat'; ofType: null; } }; 'competition': { name: 'competition'; type: { kind: 'OBJECT'; name: 'CompetitionPreviewCompat'; ofType: null; } }; 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'dateISO': { name: 'dateISO'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'fixture': { name: 'fixture'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'home': { name: 'home'; type: { kind: 'OBJECT'; name: 'TeamPreviewCompat'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'matchDay': { name: 'matchDay'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'result': { name: 'result'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'time': { name: 'time'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'TeamPreviewCompat': { kind: 'OBJECT'; name: 'TeamPreviewCompat'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'logo': { name: 'logo'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'TeamQuery': { kind: 'OBJECT'; name: 'TeamQuery'; fields: { 'details': { name: 'details'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Team'; ofType: null; }; } }; 'players': { name: 'players'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; }; }; } }; }; };
    'TeamSearchResult': { kind: 'OBJECT'; name: 'TeamSearchResult'; fields: { 'score': { name: 'score'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'team': { name: 'team'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Team'; ofType: null; }; } }; }; };
    'Tournament': { kind: 'OBJECT'; name: 'Tournament'; fields: { 'category': { name: 'category'; type: { kind: 'OBJECT'; name: 'Category'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'isLive': { name: 'isLive'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'priority': { name: 'priority'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'uniqueTournament': { name: 'uniqueTournament'; type: { kind: 'OBJECT'; name: 'UniqueTournament'; ofType: null; } }; }; };
    'UniqueTournament': { kind: 'OBJECT'; name: 'UniqueTournament'; fields: { 'category': { name: 'category'; type: { kind: 'OBJECT'; name: 'Category'; ofType: null; } }; 'displayInverseHomeAwayTeams': { name: 'displayInverseHomeAwayTeams'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'primaryColorHex': { name: 'primaryColorHex'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'secondaryColorHex': { name: 'secondaryColorHex'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'userCount': { name: 'userCount'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'UniqueTournamentSearchResult': { kind: 'OBJECT'; name: 'UniqueTournamentSearchResult'; fields: { 'score': { name: 'score'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'uniqueTournament': { name: 'uniqueTournament'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UniqueTournament'; ofType: null; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: 'sofascore';
  query: 'Query';
  mutation: never;
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';
